[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "cl1p"
author = "Maulik Patel"
author-email = "maulikp163@gmail.com"
home-page = "https://github.com/maulik9898/cl1p"
classifiers = ["License :: OSI Approved :: MIT License"]

